name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: magikcypress/personal-root-website-vuepress
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/src/.vuepress/dist/

    - name: ipfs-action
      uses: aquiladev/ipfs-action@v0.1.1
      id: upload
      with:
        path: docs/src/.vuepress/dist/
